BRONZE_CATALOG = "workspace"
BRONZE_SCHEMA = "bronze"

BRONZE_USERS_TABLE = f"{BRONZE_CATALOG}.{BRONZE_SCHEMA}.users"
BRONZE_PRODUCT_VIEWS_TABLE = f"{BRONZE_CATALOG}.{BRONZE_SCHEMA}.product_views"
BRONZE_ORDERS_TABLE = f"{BRONZE_CATALOG}.{BRONZE_SCHEMA}.orders"
BRONZE_PAYMENTS_TABLE = f"{BRONZE_CATALOG}.{BRONZE_SCHEMA}.payments"
